platform :ios, '10.0'
inhibit_all_warnings!   #去掉pod里的所有警告


target 'iOS' do
  #pod 'YYModel'
  #pod 'YYImage'
  #pod 'YYCache'
  #pod 'YYWebImage'
  #pod 'YYText'
  pod "AFNetworking"
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'Kingfisher' # 图片加载
end
